import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"font-sans"}>
        <div className="bg-[#121212] min-h-screen w-full flex justify-center">
          <div className="max-w-[450px] w-full bg-green-300 px-2">
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
